INSERT INTO CHALLENGE  VALUES
(2,PARSEDATETIME('16:12', 'HH:MM'),'java10','Obstaculo');

/*INSERT INTO ACCELERATION VALUES
(1,PARSEDATETIME('16:22', 'HH:MM'),'Java','Bolt','2');

INSERT INTO ACCELERATION VALUES
(32,PARSEDATETIME('16:22', 'HH:MM'),'Javascript','Bolt','2');*/